import {NAME} from './constants';

export const FETCH_FEED_HEADLINE = `${NAME}/FETCH_FEED_HEADLINE`;
export const FETCH_FEED_HEADLINE_FAILURE = `${NAME}/FETCH_FEED_HEADLINE_FAILURE`;
export const FETCH_FEED_HEADLINE_SUCCESS = `${NAME}/FETCH_FEED_HEADLINE_SUCCESS`;